[package]
name = "steam-controller-tracker-rs"
version = "0.1.0"
authors = ["sm-Fifteen <riboshom@hotmail.com>"]

[dependencies]
openmpt = "^0.3"
libusb = "0.3.0"
libusb-sys = "^0.2"
byteorder = "1"
clap = "2.26.0"
crossbeam = "0.3.0"